name: Ibis eBook Generation
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: '0'
    - name: Build Ibis Export Files
      uses: bobbyiliev/ibis-build-action@0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IBIS_PATH: './ebook/en/'
        IBIS_BRANCH: 'main'
        EMAIL: 'dennis@asciiden.com'
        COMMIT_MESSAGE: 'Updated Ibis Exorted Files'
